### ISSUE TITLE
gorun doesn't work when I put a function in another file

### ISSUE THREAD

**Issue by rayz-bee** [erning/gorun#25]
1. Write a simple `main.go` file under my working directory:

   ```go
   #!/Users/ray/go/bin/gorun
   package main
   
   func main() {
     PrintHello()
   }
   
   func PrintHello() {
     println("Hello, world!")
   }
   ```

   It works well when I type `gorun main.go`.

2. Move the `PrintHello` function to another file under the same folder:

   ```go
   // main.go
   #!/Users/ray/go/bin/gorun
   package main
   
   func main() {
     PrintHello()
   }
   
   // print_hello.go
   package main
   
   func PrintHello() {
     println("Hello, world!")
   }
   ```

   This time `gorun` wouldn't work. The error message gives `undefined: PrintHello`. I type `go run main.go print_hello.go`, and it works well. So I try `gorun main.go print_hello.go`, but it doesn't work anyway.

**Comment by tech10** [comment]
From the readme, I'm not sure gorun was designed to be an extensive and complex replacement for the actual go run command.

This doesn't work because go itself won't allow you to indluce one files go content from within another file. As a result, gorun is unable to include your other files with various functions that may be in them. For those types of complex setups, you should probably use go run instead of gorun.

From my understanding, gorun is designed to be simple, in that you'll include all functions and imported packages, along with the code you wish to run, within a single file. the inclusion of multiple files might be a bit more complicated to implement, especially if you want to execute a go file without using gorun, and instead, using gorun from within the file, then making that file executable as you would a bash script.

**Comment by rayz-bee** [comment]
> From the readme, I'm not sure gorun was designed to be an extensive and complex replacement for the actual go run command.
> 
> This doesn't work because go itself won't allow you to indluce one files go content from within another file. As a result, gorun is unable to include your other files with various functions that may be in them. For those types of complex setups, you should probably use go run instead of gorun.
> 
> From my understanding, gorun is designed to be simple, in that you'll include all functions and imported packages, along with the code you wish to run, within a single file. the inclusion of multiple files might be a bit more complicated to implement, especially if you want to execute a go file without using gorun, and instead, using gorun from within the file, then making that file executable as you would a bash script.

I understand. Thanks!
